### ISSUE TITLE
flaky test: shouldEvaluate3N_IIL

### ISSUE THREAD

**Issue by danielnorberg** [spotify/flo#118]
`TaskTest.shouldEvaluate3N_IIL` sometimes fails with the below error:

```
java.lang.AssertionError: timeout while waiting for 0 concurrent tasks to run

	at org.junit.Assert.fail(Assert.java:88)
	at com.spotify.flo.ControlledBlockingContext.waitUntilNumConcurrent(ControlledBlockingContext.java:63)
	at com.spotify.flo.TaskTest.validateEvaluation(TaskTest.java:201)
	at com.spotify.flo.TaskTest.shouldEvaluate3N_IIL(TaskTest.java:150)
```

**Comment by danielnorberg** [comment]
@rouzwawi Do you think this is due to a real issue in how flo executes task graphs or just a bug in the test?

**Comment by rouzwawi** [comment]
@danielnorberg PTAL
